---
experiment:
  name: asp/utzappos
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: asp
  partial: false
  gumbel: false
  kbfile: /home/ans/CZSL/ASP/utils/zappos_conceptnet.npy
  dropout: true
  norm: true
  nlayers: 2
  relu: false
  fc_emb: 768,1024,1200
  emb_dim: 300
  emb_init: fasttext
  eval_type: otherdist
  image_extractor: resnet18
  train_only: true
  static_inp: false
  composition: mlp_add
  input_dim: 300
training:
  batch_size: 256
  eval_val_every: 3
  load: 
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  max_epochs: 120
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: false
  freeze_features: false
